/**
 * Smackmap API
 *
 * Smackmap API
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.smackmap.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param smackLocationId 
 * @param smackerId 
 * @param smackerPartnerId 
 */

data class CreateSmackRequest (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "smackLocationId")
    val smackLocationId: kotlin.Long? = null,

    @Json(name = "smackerId")
    val smackerId: kotlin.Long? = null,

    @Json(name = "smackerPartnerId")
    val smackerPartnerId: kotlin.Long? = null

)

