/**
 * Smackmap API
 *
 * Smackmap API
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.smackmap.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param initiatorId 
 * @param respondentId 
 * @param response 
 */

data class RespondPartnershipRequest (

    @Json(name = "initiatorId")
    val initiatorId: kotlin.Long? = null,

    @Json(name = "respondentId")
    val respondentId: kotlin.Long? = null,

    @Json(name = "response")
    val response: RespondPartnershipRequest.Response? = null

) {

    /**
     * 
     *
     * Values: aCCEPT,dENY
     */
    enum class Response(val value: kotlin.String) {
        @Json(name = "ACCEPT") aCCEPT("ACCEPT"),
        @Json(name = "DENY") dENY("DENY");
    }
}

