/**
 * Smackmap API
 *
 * Smackmap API
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.smackmap.api.client.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param smacks 
 * @param smackLocations 
 * @param smackLocationReviews 
 */

data class SmackListDto (

    @Json(name = "smacks")
    val smacks: kotlin.collections.List<SmackDto>? = null,

    @Json(name = "smackLocations")
    val smackLocations: kotlin.collections.List<SmackLocationDto>? = null,

    @Json(name = "smackLocationReviews")
    val smackLocationReviews: kotlin.collections.List<SmackLocationReviewDto>? = null

)

