/**
 * Smackmap API
 *
 * Smackmap API
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.smackmap.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param userName 
 * @param relation 
 */

data class SmackerViewDto (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "userName")
    val userName: kotlin.String? = null,

    @Json(name = "relation")
    val relation: SmackerViewDto.Relation? = null

) {

    /**
     * 
     *
     * Values: pARTNER,fOLLOWING,bLOCKED,nOTHING
     */
    enum class Relation(val value: kotlin.String) {
        @Json(name = "PARTNER") pARTNER("PARTNER"),
        @Json(name = "FOLLOWING") fOLLOWING("FOLLOWING"),
        @Json(name = "BLOCKED") bLOCKED("BLOCKED"),
        @Json(name = "NOTHING") nOTHING("NOTHING");
    }
}

