/**
 * Smackmap API
 *
 * Smackmap API
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.smackmap.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param smackId 
 * @param reviewerId 
 * @param smackLocationId 
 * @param reviewText 
 * @param reviewStars 
 */

data class SmackLocationReviewDto (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "smackId")
    val smackId: kotlin.Long? = null,

    @Json(name = "reviewerId")
    val reviewerId: kotlin.Long? = null,

    @Json(name = "smackLocationId")
    val smackLocationId: kotlin.Long? = null,

    @Json(name = "reviewText")
    val reviewText: kotlin.String? = null,

    @Json(name = "reviewStars")
    val reviewStars: kotlin.Int? = null

)

