/**
 * Smackmap API
 *
 * Smackmap API
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.smackmap.api.client.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param smackerId 
 * @param partnerships 
 */

data class SmackerPartnershipsResponse (

    @Json(name = "smackerId")
    val smackerId: kotlin.Long? = null,

    @Json(name = "partnerships")
    val partnerships: kotlin.collections.List<PartnershipResponse>? = null

)

