/**
 * Smackmap API
 *
 * Smackmap API
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.smackmap.api.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param latFrom 
 * @param longFrom 
 * @param latTo 
 * @param longTo 
 * @param limit 
 */

data class SmackLocationSearchRequest (

    @Json(name = "latFrom")
    val latFrom: kotlin.Double? = null,

    @Json(name = "longFrom")
    val longFrom: kotlin.Double? = null,

    @Json(name = "latTo")
    val latTo: kotlin.Double? = null,

    @Json(name = "longTo")
    val longTo: kotlin.Double? = null,

    @Json(name = "limit")
    val limit: kotlin.Int? = null

)

