/**
 * Smackmap API
 *
 * Smackmap API
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.smackmap.api.client.apis

import org.openapitools.client.models.ContinuationObject
import org.openapitools.client.models.PartnershipResponse
import org.openapitools.client.models.RequestPartnershipRequest
import org.openapitools.client.models.RespondPartnershipRequest
import org.openapitools.client.models.SmackerPartnershipsResponse

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success

class PartnershipControllerApi(basePath: kotlin.String = defaultBasePath) : ApiClient(basePath) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty("org.openapitools.client.baseUrl", "http://192.168.0.58:8090")
        }
    }

    /**
    * 
    * 
    * @param smackerId  
    * @param dollarCompletion  (optional)
    * @return SmackerPartnershipsResponse
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getSmackerPartnerships(smackerId: kotlin.Long, dollarCompletion: ContinuationObject?) : SmackerPartnershipsResponse {
        val localVariableConfig = getSmackerPartnershipsRequestConfig(smackerId = smackerId, dollarCompletion = dollarCompletion)

        val localVarResponse = request<Unit, SmackerPartnershipsResponse>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SmackerPartnershipsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation getSmackerPartnerships
    *
    * @param smackerId  
    * @param dollarCompletion  (optional)
    * @return RequestConfig
    */
    fun getSmackerPartnershipsRequestConfig(smackerId: kotlin.Long, dollarCompletion: ContinuationObject?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, List<kotlin.String>>()
            .apply {
                put("smackerId", listOf(smackerId.toString()))
                if (dollarCompletion != null) {
                    put("$completion", listOf(dollarCompletion.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/partnership",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * 
    * 
    * @param requestPartnershipRequest  
    * @param dollarCompletion  (optional)
    * @return PartnershipResponse
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun requestPartnership(requestPartnershipRequest: RequestPartnershipRequest, dollarCompletion: ContinuationObject?) : PartnershipResponse {
        val localVariableConfig = requestPartnershipRequestConfig(requestPartnershipRequest = requestPartnershipRequest, dollarCompletion = dollarCompletion)

        val localVarResponse = request<RequestPartnershipRequest, PartnershipResponse>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PartnershipResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation requestPartnership
    *
    * @param requestPartnershipRequest  
    * @param dollarCompletion  (optional)
    * @return RequestConfig
    */
    fun requestPartnershipRequestConfig(requestPartnershipRequest: RequestPartnershipRequest, dollarCompletion: ContinuationObject?) : RequestConfig<RequestPartnershipRequest> {
        val localVariableBody = requestPartnershipRequest
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, List<kotlin.String>>()
            .apply {
                if (dollarCompletion != null) {
                    put("$completion", listOf(dollarCompletion.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/partnership/requestPartnership",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * 
    * 
    * @param respondPartnershipRequest  
    * @param dollarCompletion  (optional)
    * @return SmackerPartnershipsResponse
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun respondPartnership(respondPartnershipRequest: RespondPartnershipRequest, dollarCompletion: ContinuationObject?) : SmackerPartnershipsResponse {
        val localVariableConfig = respondPartnershipRequestConfig(respondPartnershipRequest = respondPartnershipRequest, dollarCompletion = dollarCompletion)

        val localVarResponse = request<RespondPartnershipRequest, SmackerPartnershipsResponse>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SmackerPartnershipsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation respondPartnership
    *
    * @param respondPartnershipRequest  
    * @param dollarCompletion  (optional)
    * @return RequestConfig
    */
    fun respondPartnershipRequestConfig(respondPartnershipRequest: RespondPartnershipRequest, dollarCompletion: ContinuationObject?) : RequestConfig<RespondPartnershipRequest> {
        val localVariableBody = respondPartnershipRequest
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, List<kotlin.String>>()
            .apply {
                if (dollarCompletion != null) {
                    put("$completion", listOf(dollarCompletion.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/partnership/respondPartnership",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

}
