/**
 * Smackmap API
 *
 * Smackmap API
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.smackmap.api.client.apis

import org.openapitools.client.models.ContinuationObject
import org.openapitools.client.models.CreateSmackLocationRequest
import org.openapitools.client.models.SmackLocationDto
import org.openapitools.client.models.SmackLocationReviewRequest
import org.openapitools.client.models.SmackLocationSearchRequest

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success

class SmackLocationControllerApi(basePath: kotlin.String = defaultBasePath) : ApiClient(basePath) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty("org.openapitools.client.baseUrl", "http://192.168.0.58:8090")
        }
    }

    /**
    * 
    * 
    * @param createSmackLocationRequest  
    * @param dollarCompletion  (optional)
    * @return SmackLocationDto
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun create1(createSmackLocationRequest: CreateSmackLocationRequest, dollarCompletion: ContinuationObject?) : SmackLocationDto {
        val localVariableConfig = create1RequestConfig(createSmackLocationRequest = createSmackLocationRequest, dollarCompletion = dollarCompletion)

        val localVarResponse = request<CreateSmackLocationRequest, SmackLocationDto>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SmackLocationDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation create1
    *
    * @param createSmackLocationRequest  
    * @param dollarCompletion  (optional)
    * @return RequestConfig
    */
    fun create1RequestConfig(createSmackLocationRequest: CreateSmackLocationRequest, dollarCompletion: ContinuationObject?) : RequestConfig<CreateSmackLocationRequest> {
        val localVariableBody = createSmackLocationRequest
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, List<kotlin.String>>()
            .apply {
                if (dollarCompletion != null) {
                    put("$completion", listOf(dollarCompletion.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/smack/location",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * 
    * 
    * @param smackLocationReviewRequest  
    * @param dollarCompletion  (optional)
    * @return SmackLocationDto
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun reviewLocation(smackLocationReviewRequest: SmackLocationReviewRequest, dollarCompletion: ContinuationObject?) : SmackLocationDto {
        val localVariableConfig = reviewLocationRequestConfig(smackLocationReviewRequest = smackLocationReviewRequest, dollarCompletion = dollarCompletion)

        val localVarResponse = request<SmackLocationReviewRequest, SmackLocationDto>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SmackLocationDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation reviewLocation
    *
    * @param smackLocationReviewRequest  
    * @param dollarCompletion  (optional)
    * @return RequestConfig
    */
    fun reviewLocationRequestConfig(smackLocationReviewRequest: SmackLocationReviewRequest, dollarCompletion: ContinuationObject?) : RequestConfig<SmackLocationReviewRequest> {
        val localVariableBody = smackLocationReviewRequest
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, List<kotlin.String>>()
            .apply {
                if (dollarCompletion != null) {
                    put("$completion", listOf(dollarCompletion.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/smack/location/review",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * 
    * 
    * @param smackLocationSearchRequest  
    * @param dollarCompletion  (optional)
    * @return kotlin.Any
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun search(smackLocationSearchRequest: SmackLocationSearchRequest, dollarCompletion: ContinuationObject?) : kotlin.Any {
        val localVariableConfig = searchRequestConfig(smackLocationSearchRequest = smackLocationSearchRequest, dollarCompletion = dollarCompletion)

        val localVarResponse = request<SmackLocationSearchRequest, kotlin.Any>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation search
    *
    * @param smackLocationSearchRequest  
    * @param dollarCompletion  (optional)
    * @return RequestConfig
    */
    fun searchRequestConfig(smackLocationSearchRequest: SmackLocationSearchRequest, dollarCompletion: ContinuationObject?) : RequestConfig<SmackLocationSearchRequest> {
        val localVariableBody = smackLocationSearchRequest
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, List<kotlin.String>>()
            .apply {
                if (dollarCompletion != null) {
                    put("$completion", listOf(dollarCompletion.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/smack/location/search",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

}
